name: cv-annot
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pytorch
  - torchvision
  - pip:
    - fiftyone
    - datumaro  # dataset conversion
    - jupyterlab
    - ipywidgets
    - tqdm
    - yacs
    - python-dotenv
    - pycocotools
    - flickrapi  # flickr image retrieval